import { useEffect, useMemo, useState } from "react";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlineIcon from "@mui/icons-material/Delete";
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { createPurchase, getProducts, getPurchases, getSuppliers } from "../modules/purchases/services/purchaseService";

const today = () => new Date().toISOString().slice(0, 10);
const newItem = { productId: "", quantity: 1, purchasePrice: 0 };
const errorMessage = (error) => error.response?.data?.message ?? "The purchase could not be completed.";

export default function PurchasePage() {
  const [purchases, setPurchases] = useState([]); const [suppliers, setSuppliers] = useState([]); const [products, setProducts] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ purchaseCode: "", purchaseDate: today(), supplierId: "", purchaseItems: [newItem] }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const supplierNames = useMemo(() => new Map(suppliers.map((supplier) => [supplier.id, supplier.supplierName])), [suppliers]);
  async function load() { try { const [purchaseData, supplierData, productData] = await Promise.all([getPurchases(), getSuppliers(), getProducts()]); setPurchases(purchaseData); setSuppliers(supplierData); setProducts(productData); } catch (requestError) { setError(errorMessage(requestError)); } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
  function resetForm() { setForm({ purchaseCode: "", purchaseDate: today(), supplierId: "", purchaseItems: [newItem] }); }
  function updateItem(index, key, value) { setForm((current) => ({ ...current, purchaseItems: current.purchaseItems.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: ["productId", "quantity", "purchasePrice"].includes(key) && value !== "" ? Number(value) : value } : item) })); }
  const total = form.purchaseItems.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.purchasePrice || 0), 0);
  async function submit(event) { event.preventDefault(); if (!form.purchaseCode.trim() || !form.supplierId || !form.purchaseItems.length || form.purchaseItems.some((item) => !item.productId || item.quantity <= 0 || item.purchasePrice < 0)) return setError("Enter a code, supplier, and valid purchase line items."); setSaving(true); try { await createPurchase({ ...form, supplierId: Number(form.supplierId), purchaseItems: form.purchaseItems.map((item) => ({ ...item, totalPrice: item.quantity * item.purchasePrice })) }); setOpen(false); resetForm(); setError(""); await load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } }
  return <Stack spacing={3}><Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between" }}><Box><Typography variant="h4">Purchases</Typography><Typography color="text.secondary">Record supplier stock purchases and update inventory.</Typography></Box><Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => { resetForm(); setOpen(true); }}>Record purchase</Button></Stack>{error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}
    <Paper sx={{ overflowX: "auto" }}><Table><TableHead><TableRow><TableCell>Purchase code</TableCell><TableCell>Date</TableCell><TableCell>Supplier</TableCell><TableCell>Items</TableCell><TableCell align="right">Total</TableCell></TableRow></TableHead><TableBody>{purchases.map((purchase) => <TableRow key={purchase.id} hover><TableCell>{purchase.purchaseCode}</TableCell><TableCell>{purchase.purchaseDate}</TableCell><TableCell>{supplierNames.get(purchase.supplierId) ?? `Supplier #${purchase.supplierId}`}</TableCell><TableCell>{purchase.purchaseItems?.length ?? 0}</TableCell><TableCell align="right">₹{purchase.totalAmount ?? 0}</TableCell></TableRow>)}{!purchases.length && <TableRow><TableCell colSpan={5} align="center">No purchases recorded.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} maxWidth="md" fullWidth slotProps={{ paper: { component: "form", onSubmit: submit } }}><DialogTitle>Record purchase</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Purchase code" required value={form.purchaseCode} onChange={(e) => setForm({ ...form, purchaseCode: e.target.value })} /><TextField label="Purchase date" required type="date" slotProps={{ inputLabel: { shrink: true } }} value={form.purchaseDate} onChange={(e) => setForm({ ...form, purchaseDate: e.target.value })} /><TextField label="Supplier" required select value={form.supplierId} onChange={(e) => setForm({ ...form, supplierId: e.target.value })}>{suppliers.map((supplier) => <MenuItem key={supplier.id} value={supplier.id}>{supplier.supplierName}</MenuItem>)}</TextField><Typography variant="h6">Line items</Typography>{form.purchaseItems.map((item, index) => <Stack direction={{ xs: "column", md: "row" }} spacing={1} key={index}><TextField select label="Product" required fullWidth value={item.productId} onChange={(e) => updateItem(index, "productId", e.target.value)}>{products.map((product) => <MenuItem key={product.id} value={product.id}>{product.productName}</MenuItem>)}</TextField><TextField label="Quantity" type="number" required slotProps={{ htmlInput: { min: 1 } }} value={item.quantity} onChange={(e) => updateItem(index, "quantity", e.target.value)} /><TextField label="Purchase price" type="number" required slotProps={{ htmlInput: { min: 0, step: "0.01" } }} value={item.purchasePrice} onChange={(e) => updateItem(index, "purchasePrice", e.target.value)} /><IconButton aria-label="Remove item" color="error" disabled={form.purchaseItems.length === 1} onClick={() => setForm({ ...form, purchaseItems: form.purchaseItems.filter((_, itemIndex) => itemIndex !== index) })}><DeleteOutlineIcon /></IconButton></Stack>)}<Button onClick={() => setForm({ ...form, purchaseItems: [...form.purchaseItems, newItem] })}>Add line item</Button><Typography align="right" variant="h6">Total: ₹{total.toFixed(2)}</Typography></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Saving…" : "Save purchase"}</Button></DialogActions></Dialog>
  </Stack>;
}
