import { useEffect, useMemo, useState } from "react";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlineIcon from "@mui/icons-material/Delete";
import PictureAsPdfOutlinedIcon from "@mui/icons-material/PictureAsPdfOutlined";
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { createSale, deleteSale, getCustomers, getInvoice, getProducts, getSales } from "../modules/sales/services/saleService";

const today = () => new Date().toISOString().slice(0, 10);
const blankItem = { productId: "", quantity: 1, sellingPrice: 0 };
const errorMessage = (error) => error.response?.data?.message ?? "The sale could not be completed.";

export default function SalePage() {
  const [sales, setSales] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ saleCode: "", saleDate: today(), customerId: "", saleItems: [blankItem] }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const customerNames = useMemo(() => new Map(customers.map((customer) => [customer.id, customer.customerName])), [customers]);
  async function load() { try { const [saleData, customerData, productData] = await Promise.all([getSales(), getCustomers(), getProducts()]); setSales(saleData); setCustomers(customerData); setProducts(productData.filter((product) => product.active !== false)); } catch (requestError) { setError(errorMessage(requestError)); } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
  function resetForm() { setForm({ saleCode: "", saleDate: today(), customerId: "", saleItems: [blankItem] }); }
  function updateItem(index, key, value) { const numeric = ["productId", "quantity", "sellingPrice"].includes(key); setForm((current) => ({ ...current, saleItems: current.saleItems.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: numeric && value !== "" ? Number(value) : value } : item) })); }
  function selectProduct(index, id) { const product = products.find((entry) => entry.id === Number(id)); updateItem(index, "productId", id); if (product) updateItem(index, "sellingPrice", product.sellingPrice ?? 0); }
  const total = form.saleItems.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.sellingPrice || 0), 0);
  async function submit(event) { event.preventDefault(); if (!form.saleCode.trim() || !form.customerId || form.saleItems.some((item) => !item.productId || item.quantity <= 0 || item.sellingPrice < 0)) return setError("Enter a sale code, customer, and valid line items."); setSaving(true); try { await createSale({ ...form, customerId: Number(form.customerId), saleItems: form.saleItems.map((item) => ({ ...item, totalPrice: item.quantity * item.sellingPrice })) }); setOpen(false); resetForm(); setError(""); await load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } }
  async function remove(id) { if (!window.confirm("Cancel this sale? This action cannot be undone.")) return; try { await deleteSale(id); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function invoice(id) { try { const response = await getInvoice(id); const url = URL.createObjectURL(response.data); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (requestError) { setError(errorMessage(requestError)); } }
  return <Stack spacing={3}><Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between" }}><Box><Typography variant="h4">Sales</Typography><Typography color="text.secondary">Create customer sales and reduce inventory automatically.</Typography></Box><Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => { resetForm(); setOpen(true); }}>New sale</Button></Stack>{error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}
    <Paper sx={{ overflowX: "auto" }}><Table><TableHead><TableRow><TableCell>Sale code</TableCell><TableCell>Date</TableCell><TableCell>Customer</TableCell><TableCell>Items</TableCell><TableCell align="right">Total</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{sales.map((sale) => <TableRow key={sale.id} hover><TableCell>{sale.saleCode}</TableCell><TableCell>{sale.saleDate}</TableCell><TableCell>{customerNames.get(sale.customerId) ?? `Customer #${sale.customerId}`}</TableCell><TableCell>{sale.saleItems?.length ?? 0}</TableCell><TableCell align="right">₹{sale.totalAmount ?? 0}</TableCell><TableCell align="right"><IconButton aria-label="Open invoice" onClick={() => invoice(sale.id)}><PictureAsPdfOutlinedIcon /></IconButton><IconButton aria-label="Delete sale" color="error" onClick={() => remove(sale.id)}><DeleteOutlineIcon /></IconButton></TableCell></TableRow>)}{!sales.length && <TableRow><TableCell colSpan={6} align="center">No sales recorded.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} maxWidth="md" fullWidth slotProps={{ paper: { component: "form", onSubmit: submit } }}><DialogTitle>New sale</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Sale code" required value={form.saleCode} onChange={(e) => setForm({ ...form, saleCode: e.target.value })} /><TextField label="Sale date" required type="date" slotProps={{ inputLabel: { shrink: true } }} value={form.saleDate} onChange={(e) => setForm({ ...form, saleDate: e.target.value })} /><TextField label="Customer" required select value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}>{customers.map((customer) => <MenuItem key={customer.id} value={customer.id}>{customer.customerName}</MenuItem>)}</TextField><Typography variant="h6">Line items</Typography>{form.saleItems.map((item, index) => <Stack direction={{ xs: "column", md: "row" }} spacing={1} key={index}><TextField label="Product" required select fullWidth value={item.productId} onChange={(e) => selectProduct(index, e.target.value)}>{products.map((product) => <MenuItem key={product.id} value={product.id} disabled={product.quantity <= 0}>{product.productName} ({product.quantity} {product.unit})</MenuItem>)}</TextField><TextField label="Quantity" type="number" required slotProps={{ htmlInput: { min: 1 } }} value={item.quantity} onChange={(e) => updateItem(index, "quantity", e.target.value)} /><TextField label="Selling price" type="number" required slotProps={{ htmlInput: { min: 0, step: "0.01" } }} value={item.sellingPrice} onChange={(e) => updateItem(index, "sellingPrice", e.target.value)} /><IconButton aria-label="Remove item" color="error" disabled={form.saleItems.length === 1} onClick={() => setForm({ ...form, saleItems: form.saleItems.filter((_, itemIndex) => itemIndex !== index) })}><DeleteOutlineIcon /></IconButton></Stack>)}<Button onClick={() => setForm({ ...form, saleItems: [...form.saleItems, blankItem] })}>Add line item</Button><Typography align="right" variant="h6">Total: ₹{total.toFixed(2)}</Typography></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Saving…" : "Save sale"}</Button></DialogActions></Dialog>
  </Stack>;
}
