import { useEffect, useMemo, useState } from "react";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlineIcon from "@mui/icons-material/Delete";
import PictureAsPdfOutlinedIcon from "@mui/icons-material/PictureAsPdfOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { createSale, deleteSale, getCustomers, getInvoice, getProducts, getSales } from "../modules/sales/services/saleService";
import { productLabel } from "../modules/products/productLabel";

const PAGE_SIZE = 20;
const today = () => new Date().toISOString().slice(0, 10);
const blankItem = { productId: "", quantity: 1, sellingPrice: 0 };
const errorMessage = (error) => error.response?.data?.message ?? "The sale could not be completed.";
const money = (value) => `₹${Number(value ?? 0).toFixed(2)}`;
const dateValue = (date) => new Date(`${date}T00:00:00`);

function inDateFilter(saleDate, filter, from, to) {
  const sale = dateValue(saleDate); const now = dateValue(today());
  if (filter === "today") return saleDate === today();
  if (filter === "yesterday") { const yesterday = new Date(now); yesterday.setDate(now.getDate() - 1); return saleDate === yesterday.toISOString().slice(0, 10); }
  if (filter === "week") { const start = new Date(now); start.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return sale >= start && sale <= now; }
  if (filter === "month") return sale.getFullYear() === now.getFullYear() && sale.getMonth() === now.getMonth();
  return filter !== "custom" || ((!from || saleDate >= from) && (!to || saleDate <= to));
}

export default function SalePage() {
  const [sales, setSales] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]);
  const [open, setOpen] = useState(false); const [details, setDetails] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [query, setQuery] = useState(""); const [dateFilter, setDateFilter] = useState("all"); const [paymentFilter, setPaymentFilter] = useState("all"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [sort, setSort] = useState("date"); const [direction, setDirection] = useState("desc"); const [page, setPage] = useState(1);
  const [form, setForm] = useState({ saleDate: today(), customerId: "", paymentMethod: "Cash", saleItems: [blankItem] });
  const customerById = useMemo(() => new Map(customers.map((customer) => [customer.id, customer])), [customers]);
  const productById = useMemo(() => new Map(products.map((product) => [product.id, product])), [products]);
  const customerLabel = (sale) => customerById.get(sale.customerId)?.customerName ?? `Customer #${sale.customerId}`;
  async function load() { try { const [saleData, customerData, productData] = await Promise.all([getSales(), getCustomers(), getProducts()]); setSales(saleData); setCustomers(customerData); setProducts(productData); } catch (requestError) { setError(errorMessage(requestError)); } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
  function resetForm() { setForm({ saleDate: today(), customerId: "", paymentMethod: "Cash", saleItems: [blankItem] }); }
  function selectCustomer(customerId) { const customer = customerById.get(Number(customerId)); const creditEnabled = customer?.creditEnabled ?? Number(customer?.creditLimit ?? 0) > 0; setForm((current) => ({ ...current, customerId, paymentMethod: creditEnabled ? current.paymentMethod : "Cash" })); }
  function updateItem(index, key, value) { const numeric = ["productId", "quantity", "sellingPrice"].includes(key); setForm((current) => ({ ...current, saleItems: current.saleItems.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: numeric && value !== "" ? Number(value) : value } : item) })); }
  function selectProduct(index, id) { const product = productById.get(Number(id)); updateItem(index, "productId", id); if (product) updateItem(index, "sellingPrice", product.sellingPrice ?? 0); }
  const total = form.saleItems.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.sellingPrice || 0), 0);
  const filteredSales = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return sales.filter((sale) => {
      const customer = customerById.get(sale.customerId); const searchable = [customer?.customerName, customer?.phone, sale.saleCode, sale.id, sale.saleDate, sale.paymentMethod].filter(Boolean).join(" ").toLowerCase();
      return (!normalizedQuery || searchable.includes(normalizedQuery)) && inDateFilter(sale.saleDate, dateFilter, fromDate, toDate) && (paymentFilter === "all" || (sale.paymentMethod || "Cash").toLowerCase() === paymentFilter);
    }).sort((first, second) => {
      let compare = 0;
      if (sort === "date") compare = String(first.saleDate).localeCompare(String(second.saleDate)) || Number(first.id) - Number(second.id);
      if (sort === "customer") compare = (customerById.get(first.customerId)?.customerName ?? "").localeCompare(customerById.get(second.customerId)?.customerName ?? "");
      if (sort === "total") compare = Number(first.totalAmount ?? 0) - Number(second.totalAmount ?? 0);
      return direction === "asc" ? compare : -compare;
    });
  }, [sales, customerById, query, dateFilter, paymentFilter, fromDate, toDate, sort, direction]);
  const pageCount = Math.max(1, Math.ceil(filteredSales.length / PAGE_SIZE)); const currentPage = Math.min(page, pageCount); const visibleSales = filteredSales.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  function chooseSort(field) { if (sort === field) setDirection((current) => current === "asc" ? "desc" : "asc"); else { setSort(field); setDirection(field === "date" ? "desc" : "asc"); } }
  async function submit(event) { event.preventDefault(); const customer = customerById.get(Number(form.customerId)); const creditEnabled = customer?.creditEnabled ?? Number(customer?.creditLimit ?? 0) > 0; if (!form.customerId || !form.saleItems.length || (form.paymentMethod === "Credit" && !creditEnabled) || form.saleItems.some((item) => !item.productId || item.quantity <= 0 || item.sellingPrice < 0)) return setError(form.paymentMethod === "Credit" ? "Only credit-enabled customers can use Credit payment." : "Choose a customer and valid sale items."); setSaving(true); try { await createSale({ ...form, customerId: Number(form.customerId), saleItems: form.saleItems.map((item) => ({ ...item, totalPrice: item.quantity * item.sellingPrice })) }); setOpen(false); resetForm(); setError(""); await load(); } catch (requestError) { setError(errorMessage(requestError)); } finally { setSaving(false); } }
  async function remove(id) { if (!window.confirm("Delete this sale? The sold stock will be returned to inventory.")) return; try { await deleteSale(id); if (details?.id === id) setDetails(null); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function invoice(id) { try { const response = await getInvoice(id); const url = URL.createObjectURL(response.data); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (requestError) { setError(errorMessage(requestError)); } }
  const pageNumbers = Array.from({ length: pageCount }, (_, index) => index + 1).filter((number) => pageCount <= 5 || number === 1 || number === pageCount || Math.abs(number - currentPage) <= 1);
  return <Stack spacing={3}>
    <Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { sm: "center" } }}><Box><Typography variant="h4">Sales</Typography><Typography color="text.secondary">Create customer sales and reduce inventory automatically.</Typography></Box><Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => { resetForm(); setOpen(true); }}>New sale</Button></Stack>
    {error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}
    <Stack direction={{ xs: "column", md: "row" }} spacing={1.5} sx={{ alignItems: { md: "center" } }}><TextField placeholder="Search sales..." value={query} onChange={(event) => setQuery(event.target.value)} size="small" sx={{ minWidth: { md: 260 }, flexGrow: { md: 1 } }} slotProps={{ htmlInput: { "aria-label": "Search sales" } }} /><TextField select label="Date" size="small" value={dateFilter} onChange={(event) => setDateFilter(event.target.value)} sx={{ minWidth: 155 }}><MenuItem value="all">All dates</MenuItem><MenuItem value="today">Today</MenuItem><MenuItem value="yesterday">Yesterday</MenuItem><MenuItem value="week">This week</MenuItem><MenuItem value="month">This month</MenuItem><MenuItem value="custom">Custom date range</MenuItem></TextField><TextField select label="Payment method" size="small" value={paymentFilter} onChange={(event) => setPaymentFilter(event.target.value)} sx={{ minWidth: 175 }}><MenuItem value="all">All</MenuItem><MenuItem value="cash">Cash</MenuItem><MenuItem value="upi">UPI</MenuItem><MenuItem value="card">Card</MenuItem><MenuItem value="credit">Credit</MenuItem></TextField></Stack>
    {dateFilter === "custom" && <Stack direction={{ xs: "column", sm: "row" }} spacing={1.5}><TextField label="From date" type="date" size="small" slotProps={{ inputLabel: { shrink: true } }} value={fromDate} onChange={(event) => setFromDate(event.target.value)} /><TextField label="To date" type="date" size="small" slotProps={{ inputLabel: { shrink: true } }} value={toDate} onChange={(event) => setToDate(event.target.value)} /></Stack>}
    <Paper sx={{ display: { xs: "none", md: "block" }, overflowX: "auto" }}><Table><TableHead><TableRow><TableCell>S.No.</TableCell><TableCell><Button size="small" onClick={() => chooseSort("date")}>Date{sort === "date" ? (direction === "asc" ? " ↑" : " ↓") : ""}</Button></TableCell><TableCell><Button size="small" onClick={() => chooseSort("customer")}>Customer{sort === "customer" ? (direction === "asc" ? " ↑" : " ↓") : ""}</Button></TableCell><TableCell>Payment</TableCell><TableCell>Items</TableCell><TableCell align="right"><Button size="small" onClick={() => chooseSort("total")}>Total{sort === "total" ? (direction === "asc" ? " ↑" : " ↓") : ""}</Button></TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{visibleSales.map((sale, index) => <TableRow key={sale.id} hover><TableCell>{(currentPage - 1) * PAGE_SIZE + index + 1}</TableCell><TableCell>{sale.saleDate}</TableCell><TableCell>{customerLabel(sale)}</TableCell><TableCell>{sale.paymentMethod || "Cash"}</TableCell><TableCell>{sale.saleItems?.length ?? 0}</TableCell><TableCell align="right">{money(sale.totalAmount)}</TableCell><TableCell align="right"><Button size="small" startIcon={<VisibilityOutlinedIcon />} onClick={() => setDetails(sale)}>View sale</Button><IconButton aria-label="Open receipt PDF" onClick={() => invoice(sale.id)}><PictureAsPdfOutlinedIcon /></IconButton><IconButton aria-label="Delete sale" color="error" onClick={() => remove(sale.id)}><DeleteOutlineIcon /></IconButton></TableCell></TableRow>)}{!visibleSales.length && <TableRow><TableCell colSpan={7} align="center">No sales found.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Stack spacing={1.25} sx={{ display: { xs: "flex", md: "none" } }}>{visibleSales.map((sale, index) => <Paper key={sale.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Typography variant="subtitle2">Sale #{(currentPage - 1) * PAGE_SIZE + index + 1}</Typography><Typography variant="h6">{customerLabel(sale)}</Typography><Typography variant="body2" color="text.secondary">{sale.saleDate} • {sale.paymentMethod || "Cash"}</Typography><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography variant="body2">{sale.saleItems?.length ?? 0} Items</Typography><Typography fontWeight={700}>{money(sale.totalAmount)}</Typography></Stack><Stack direction="row" spacing={1}><Button size="small" variant="outlined" startIcon={<VisibilityOutlinedIcon />} onClick={() => setDetails(sale)}>View</Button><Button size="small" variant="outlined" startIcon={<PictureAsPdfOutlinedIcon />} onClick={() => invoice(sale.id)}>Receipt</Button></Stack></Stack></Paper>)}{!visibleSales.length && <Paper variant="outlined" sx={{ p: 3, textAlign: "center" }}>No sales found.</Paper>}</Stack>
    {filteredSales.length > 0 && <Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ alignItems: { sm: "center" }, justifyContent: "space-between" }}><Typography variant="body2" color="text.secondary">Showing {(currentPage - 1) * PAGE_SIZE + 1}–{Math.min(currentPage * PAGE_SIZE, filteredSales.length)} of {filteredSales.length} sales</Typography><Stack direction="row" spacing={0.5} sx={{ flexWrap: "wrap" }}><Button size="small" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</Button>{pageNumbers.map((number) => <Button key={number} size="small" variant={number === currentPage ? "contained" : "text"} onClick={() => setPage(number)}>{number}</Button>)}<Button size="small" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}>Next</Button></Stack></Stack>}
    <Dialog open={Boolean(details)} onClose={() => setDetails(null)} maxWidth="sm" fullWidth><DialogTitle>Sale details</DialogTitle><DialogContent>{details && <Stack spacing={2} sx={{ pt: 1 }}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography color="text.secondary">Date</Typography><Typography>{details.saleDate}</Typography></Stack><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography color="text.secondary">Customer</Typography><Typography>{customerLabel(details)}</Typography></Stack><Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography color="text.secondary">Payment method</Typography><Typography>{details.paymentMethod || "Cash"}</Typography></Stack><Box><Typography variant="subtitle2" sx={{ mb: 1 }}>Products purchased</Typography><Table size="small"><TableHead><TableRow><TableCell>Product</TableCell><TableCell align="right">Qty</TableCell><TableCell align="right">Price</TableCell><TableCell align="right">Subtotal</TableCell></TableRow></TableHead><TableBody>{details.saleItems?.map((item) => <TableRow key={item.id ?? item.productId}><TableCell>{productById.has(item.productId) ? productLabel(productById.get(item.productId)) : `Product #${item.productId}`}</TableCell><TableCell align="right">{item.quantity}</TableCell><TableCell align="right">{money(item.sellingPrice)}</TableCell><TableCell align="right">{money(item.totalPrice ?? item.quantity * item.sellingPrice)}</TableCell></TableRow>)}</TableBody></Table></Box>{Number(details.discountAmount ?? 0) > 0 && <Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography color="text.secondary">Discount</Typography><Typography>-{money(details.discountAmount)}</Typography></Stack>}<Stack direction="row" sx={{ justifyContent: "space-between" }}><Typography variant="h6">Final total</Typography><Typography variant="h6">{money(details.totalAmount)}</Typography></Stack></Stack>}</DialogContent><DialogActions><Button onClick={() => invoice(details.id)} startIcon={<PictureAsPdfOutlinedIcon />}>Receipt/PDF</Button><Button onClick={() => setDetails(null)}>Close</Button></DialogActions></Dialog>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} maxWidth="md" fullWidth slotProps={{ paper: { component: "form", onSubmit: submit } }}><DialogTitle>New sale</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Sale date" required type="date" slotProps={{ inputLabel: { shrink: true } }} value={form.saleDate} onChange={(event) => setForm({ ...form, saleDate: event.target.value })} /><TextField label="Customer" required select value={form.customerId} onChange={(event) => selectCustomer(event.target.value)}>{customers.map((customer) => { const creditEnabled = customer.creditEnabled ?? Number(customer.creditLimit ?? 0) > 0; return <MenuItem key={customer.id} value={customer.id}>{customer.customerName}{creditEnabled ? " · Credit enabled" : " · Cash/UPI/Card only"}</MenuItem>; })}</TextField><TextField label="Payment method" required select value={form.paymentMethod} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value })}><MenuItem value="Cash">Cash</MenuItem><MenuItem value="UPI">UPI</MenuItem><MenuItem value="Card">Card</MenuItem>{(customerById.get(Number(form.customerId))?.creditEnabled ?? Number(customerById.get(Number(form.customerId))?.creditLimit ?? 0) > 0) && <MenuItem value="Credit">Credit</MenuItem>}</TextField><Typography variant="h6">Line items</Typography>{form.saleItems.map((item, index) => <Stack direction={{ xs: "column", md: "row" }} spacing={1} key={index}><TextField label="Product" required select fullWidth value={item.productId} onChange={(event) => selectProduct(index, event.target.value)}>{products.filter((product) => product.active !== false).map((product) => <MenuItem key={product.id} value={product.id} disabled={product.quantity <= 0}>{productLabel(product, { includeStock: true })}</MenuItem>)}</TextField><TextField label="Quantity" type="number" required slotProps={{ htmlInput: { min: 1 } }} value={item.quantity} onChange={(event) => updateItem(index, "quantity", event.target.value)} /><TextField label="Selling price" type="number" required slotProps={{ htmlInput: { min: 0, step: "0.01" } }} value={item.sellingPrice} onChange={(event) => updateItem(index, "sellingPrice", event.target.value)} /><IconButton aria-label="Remove item" color="error" disabled={form.saleItems.length === 1} onClick={() => setForm((current) => ({ ...current, saleItems: current.saleItems.filter((_, itemIndex) => itemIndex !== index) }))}><DeleteOutlineIcon /></IconButton></Stack>)}<Button onClick={() => setForm((current) => ({ ...current, saleItems: [...current.saleItems, blankItem] }))}>Add line item</Button><Typography align="right" variant="h6">Total: {money(total)}</Typography></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Saving…" : "Complete sale"}</Button></DialogActions></Dialog>
  </Stack>;
}
