import { useEffect, useState } from "react";
import { Html5Qrcode } from "html5-qrcode";
import QrCodeScannerOutlinedIcon from "@mui/icons-material/QrCodeScannerOutlined";
import { Alert, Autocomplete, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from "@mui/material";

const initialProduct = { productCode: "", barcode: "", productName: "", brand: "", subcategory: "", categoryId: "", variant: "", unit: "Piece", quantity: 0, purchasePrice: 0, sellingPrice: 0, minimumStock: 0, expiryApplicable: false, expiryDate: "", active: true };
const numericFields = new Set(["categoryId", "quantity", "purchasePrice", "sellingPrice", "minimumStock"]);
const subcategories = { Grocery: ["Rice", "Dal", "Flour", "Sugar", "Salt", "Spices", "Cooking Oil"], "Personal Care": ["Bath Soap", "Hand Wash", "Shampoo", "Toothpaste", "Hair Oil"], "Home Care": ["Laundry Detergent", "Dishwash", "Floor Cleaner", "Toilet Cleaner"], Beverages: ["Soft Drinks", "Juice", "Tea", "Coffee", "Health Drinks"], Snacks: ["Biscuits", "Chips", "Chocolates", "Namkeen"], "Dairy & Bakery": ["Milk", "Curd", "Butter", "Bread", "Eggs"] };

export default function ProductFormDialog({ open, product, categories, saving, onClose, onSubmit }) {
  const [form, setForm] = useState(() => product ? { ...initialProduct, ...product, categoryId: product.categoryId ?? "", expiryDate: product.expiryDate ?? "" } : initialProduct); const [error, setError] = useState(""); const [scannerOpen, setScannerOpen] = useState(false); const [scannerError, setScannerError] = useState(""); const [manualBarcode, setManualBarcode] = useState("");
  function change(key, value) { setForm((current) => ({ ...current, [key]: numericFields.has(key) && value !== "" ? Number(value) : value, ...(key === "categoryId" ? { subcategory: "" } : {}) })); }
  const categoryName = categories.find((category) => Number(category.id) === Number(form.categoryId))?.name;
  useEffect(() => { if (!scannerOpen) return undefined; let scanner; let started = false; let cancelled = false; const start = async () => { try { scanner = new Html5Qrcode("product-form-camera-reader"); await scanner.start({ facingMode: "environment" }, { fps: 10, qrbox: { width: 260, height: 160 } }, (code) => { const barcode = code.trim(); if (!barcode) return; setForm((current) => ({ ...current, barcode })); setManualBarcode(barcode); setScannerOpen(false); }, () => {}); started = true; if (cancelled) await scanner.stop(); } catch { if (!cancelled) setScannerError("Camera could not start. Allow camera access or enter the barcode below."); } }; const timer = window.setTimeout(start, 150); return () => { cancelled = true; window.clearTimeout(timer); if (scanner && started) scanner.stop().catch(() => {}); }; }, [scannerOpen]);
  function applyBarcode(value) { const barcode = value.trim(); if (!barcode) return; change("barcode", barcode); setManualBarcode(barcode); setScannerOpen(false); }
  function openScanner() { setScannerError(""); setManualBarcode(form.barcode); setScannerOpen(true); }
  function submit(event) { event.preventDefault(); if (!form.productName.trim() || form.categoryId === "" || !form.unit) return setError("Product name, category, and unit are required."); if (form.quantity < 0 || form.purchasePrice < 0 || form.sellingPrice < 0 || form.minimumStock < 0) return setError("Stock and prices cannot be negative."); if (form.sellingPrice < form.purchasePrice) return setError("Selling price cannot be lower than dealer price."); onSubmit({ ...form, barcode: form.barcode.trim(), brand: form.brand.trim(), subcategory: form.subcategory.trim(), variant: form.variant.trim() }); }
  return <Dialog open={open} onClose={() => !saving && onClose()} maxWidth="sm" fullWidth slotProps={{ paper: { component: "form", onSubmit: submit } }}><DialogTitle>{product ? "Edit product" : "Add product"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}
    <TextField label="Product name" required value={form.productName} onChange={(e) => change("productName", e.target.value)} />
    <TextField label="Category" required select value={form.categoryId} onChange={(e) => change("categoryId", e.target.value)}>{categories.filter((category) => category.active !== false || Number(category.id) === Number(form.categoryId)).map((category) => <MenuItem key={category.id} value={category.id}>{category.name}</MenuItem>)}</TextField><Autocomplete freeSolo options={subcategories[categoryName] ?? []} value={form.subcategory} onChange={(_, value) => change("subcategory", value ?? "")} onInputChange={(_, value) => change("subcategory", value)} renderInput={(params) => <TextField {...params} label="Subcategory" helperText="Choose a matching subcategory or enter a custom one." />} />
    <TextField label="Brand" value={form.brand} onChange={(e) => change("brand", e.target.value)} helperText="Enter an existing or new brand." /><TextField label="Size / variant" value={form.variant} onChange={(e) => change("variant", e.target.value)} placeholder="e.g. 100g, 1L, Pack of 10" /><Stack direction={{ xs: "column", sm: "row" }} spacing={1}><TextField fullWidth label="Barcode" value={form.barcode} onChange={(e) => change("barcode", e.target.value)} helperText="Optional, but must be unique when provided." /><Button variant="outlined" startIcon={<QrCodeScannerOutlinedIcon />} onClick={openScanner} sx={{ alignSelf: { sm: "flex-start" }, mt: { sm: 0.5 } }}>Scan</Button></Stack><TextField label="Unit" required select value={form.unit} onChange={(e) => change("unit", e.target.value)}>{["Piece", "Kg", "Gram", "Litre", "ml", "Bag", "Box", "Pack", "Bottle"].map((unit) => <MenuItem key={unit} value={unit}>{unit}</MenuItem>)}</TextField>
    <TextField label="Quantity" type="number" slotProps={{ htmlInput: { min: 0 } }} value={form.quantity} onChange={(e) => change("quantity", e.target.value)} /><TextField label="Minimum stock" type="number" slotProps={{ htmlInput: { min: 0 } }} value={form.minimumStock} onChange={(e) => change("minimumStock", e.target.value)} />
    <TextField label="Purchase price" type="number" slotProps={{ htmlInput: { min: 0, step: "0.01" } }} value={form.purchasePrice} onChange={(e) => change("purchasePrice", e.target.value)} /><TextField label="Selling price" type="number" slotProps={{ htmlInput: { min: 0, step: "0.01" } }} value={form.sellingPrice} onChange={(e) => change("sellingPrice", e.target.value)} />
    <TextField label="Status" select value={String(form.active)} onChange={(e) => change("active", e.target.value === "true")}><MenuItem value="true">Active</MenuItem><MenuItem value="false">Inactive</MenuItem></TextField>
  </Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Saving…" : "Save product"}</Button></DialogActions><Dialog open={scannerOpen} onClose={() => setScannerOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Scan new product barcode</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Typography color="text.secondary">Scan the barcode on the new product. The code will fill the form automatically.</Typography><Box id="product-form-camera-reader" sx={{ minHeight: 220, overflow: "hidden", borderRadius: 1, bgcolor: "grey.100", "& video": { width: "100%" } }} />{scannerError && <Alert severity="warning">{scannerError}</Alert>}<TextField label="Enter barcode manually" autoFocus value={manualBarcode} onChange={(e) => setManualBarcode(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); applyBarcode(e.currentTarget.value); } }} /></Stack></DialogContent><DialogActions><Button onClick={() => setScannerOpen(false)}>Cancel</Button><Button variant="contained" onClick={() => applyBarcode(manualBarcode)}>Use barcode</Button></DialogActions></Dialog></Dialog>;
}
